name: Drew Land
description: If I was a wizard I would cast spells and stuff not write code...

url: http://drewland.me
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown:    redcarpet
highlighter: pygments
paginate:    5

navigation:
 - title: Home
   url: /index
 - title: About
   url: /about
 - title: Resume
   url: /resume.pdf
